apiVersion: v1
kind: Service
metadata:
  name: pwallet-service
spec:
  type: LoadBalancer
  selector: 
    app: pwallet-testnet
  ports:  
    - protocol: TCP
      port: 3001
      targetPort: 3000
      name: http-web