apiVersion: v1
kind: Service
metadata:
  name: pwallet-service
spec:
  type: LoadBalancer
  selector: 
    app: pwallet-testnet
  ports:  
    - name: http-web
      port: 3001
      targetPort: 3000
